### ISSUE TITLE
Upgrade material-ui to its latest stable version

### ISSUE THREAD

**Issue by codejockie** [codejockie/document-manager#77]
Upgrading material-ui and material-icons to their latest stable versions is the goal of this issue.
Keep in mind that after upgrading ensure the application is not broken and client:test passes before submitting a pull request.

Good luck!!!

**Comment by viettrung9012** [comment]
let me take a stab on this

**Comment by codejockie** [comment]
@viettrung9012 sure please go ahead.

**Comment by codejockie** [comment]
@viettrung9012 there is a new version of material ui, I think 4.5.0. Please could you update this? Thank you.
